
version: 2

models:
# Customer
  - name: customer
    description: Customer table
    columns:
      - name: CustomerKey
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null  

  # Product
  - name: product
    description: Product table
    columns:
      - name: ProductKey
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: ProductSubcategoryKey
        description: "The foreign key to the product subcategory table"
  
  # Product Subcategory
  - name: product_subcategory
    description: Product Subcategory table
    columns:
      - name: ProductSubcategoryKey
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  # Product Category
  - name: product_category
    description: Product Category table
    columns:
      - name: ProductCategoryKey
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  # Sales Order Detail
  - name: internet_sales
    description: Internet sales table
    columns:
      - name: SalesOrderNumber
        description: "The primary key for this table"
        data_tests:
          - not_null