# Profiles the service principal uses to authenticate with databricks when running dbt
# Using a profile allows dbt jobs to be ran on standard compute without using a SQL warehouse
adventure_works_demo:
  target: dev
  outputs:
    dev:
      type: fabricspark
      method: livy
      endpoint: https://api.fabric.microsoft.com/v1
      workspaceid: aa623016-b8d7-436e-b4aa-4aa5b99d882c
      lakehouseid: 775686e9-f69f-408a-9c03-a8a3218a064a
      lakehouse: Adventureworks
      schema: dbt
      threads: 1

      authentication: fabric_notebook
      livy_mode: fabric

      connect_retries: 1
      connect_timeout: 10
      http_timeout: 120
      session_start_timeout: 600
      statement_timeout: 3600
      poll_wait: 10
      poll_statement_wait: 5

      retry_all: true

      spark_config:
        name: "dbt_spark_session"