version: 2

models:
  # Dim Customer
  - name: vw_dim_customer
    description: "Customer dimension table"
    columns:
      - name: CustomerID
        description: "The primary key for the vw_dim_customer table"
        data_type: int
        data_tests:
          - unique
          - not_null
        constraints:
          - type: not_null
          - type: primary_key

  # Dim Product
  - name: vw_dim_product
    description: "Product dimension table"
    columns:
      - name: ProductID
        description: "The primary key for the vw_dim_product table"
        data_tests:
          - unique
          - not_null
        constraints:
          - type: not_null
          - type: primary_key
          
  # Fact Sales
  - name: vw_fact_sales
    description: "Sales fact table"
    columns:
      - name: SalesOrderDetailID
        description: "The primary key for the fact_sales table"
        data_tests:
          - unique
          - not_null
        constraints:
          - type: not_null
          - type: primary_key
      - name: ProductID
        description: "The foreign key to the vw_dim_product table"
        constraints:
          - type: foreign_key
            to: ref('vw_dim_product')
            to_columns: [ProductID]
      - name: CustomerID
        description: "The foreign key to the vw_dim_customer table"
        constraints:
          - type: foreign_key
            to: ref('vw_dim_customer')
            to_columns: [CustomerID]
      - name: OrderDate
        description: "Date the order was placed"
        data_type: timestamp
      - name: DueDate
        description: "Date the order is due"
        data_type: timestamp
      - name: ShipDate
        description: "Date the order was shipped"
        data_type: timestamp
      - name: Status
        description: "Order status"
        data_type: int
      - name: TaxAmt
        data_type: decimal(19,4)
        description: "Tax amount for the order"
      - name: TotalDue
        data_type: decimal(19,4)
        description: "Total amount due for the order"
      - name: UnitPrice
        data_type: decimal(19,4)
        description: "Unit price of the product"
      - name: UnitPriceDiscount
        description: "Discount applied to the unit price"
        data_type: decimal(19,4)